# Generated by Django 3.2.12 on 2022-12-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0002_alter_recipient_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='phone',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='state',
            field=models.CharField(default='UnknownPreference', max_length=100),
        ),
    ]
