# Generated by Django 3.2.12 on 2022-12-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0003_auto_20221225_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='id',
        ),
        migrations.AlterField(
            model_name='recipient',
            name='phone',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='state',
            field=models.CharField(choices=[('UnknownPreference', 'UnknownPreference'), ('AffirmativePurchase', 'AffirmativePurchase')], default='UnknownPreference', max_length=20),
        ),
    ]
