# Generated by Django 3.2.12 on 2022-12-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0006_alter_recipient_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='state',
            field=models.CharField(choices=[('InvalidState', 'InvalidState'), ('UnknownPreference', 'UnknownPreference'), ('AffirmativePurchase', 'AffirmativePurchase'), ('NegativePurchase', 'NegativePurchase'), ('MetadataExists', 'MetadataExists'), ('NoneOrIncorrectMetadata', 'NoneOrIncorrectMetadata'), ('MetadataExists', 'MetadataExists'), ('CorrectMetadata', 'CorrectMetadata'), ('NoPaymentData', 'NoPaymentData'), ('PaymentRequested', 'PaymentRequested'), ('InvalidPaymentDetails', 'InvalidPaymentDetails'), ('PaymentAndMetadataCorrect', 'PaymentAndMetadataCorrect'), ('Terminate', 'Terminate')], default='UnknownPreference', max_length=30),
        ),
    ]
