# Generated by Django 3.2.12 on 2022-12-25 23:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0008_auto_20221225_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('9.5299999999999993605115378159098327159881591796875'), max_digits=6),
        ),
    ]
