# Generated by Django 3.2.12 on 2022-12-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0010_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='M', max_length=30),
        ),
    ]
