# Generated by Django 3.2.12 on 2022-12-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0011_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=2, max_length=100, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
