# Generated by Django 3.2.12 on 2022-12-26 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0012_auto_20221226_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='gender',
            new_name='genderf',
        ),
    ]
