# Generated by Django 3.2.12 on 2022-12-26 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0013_rename_gender_product_genderf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='genderf',
            new_name='gender',
        ),
    ]
