# Generated by Django 3.2.12 on 2022-12-26 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0014_rename_genderf_product_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[
                 ('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], default='Male', max_length=30)),
                ('type', models.CharField(choices=[
                 ('Tops', 'Tops'), ('Bottoms', 'Bottoms'), ('Shoes', 'Shoes')], default='Tops', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(default='M', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='texts.productcategory'),
            preserve_default=False,
        ),
    ]
