# Generated by Django 3.2.12 on 2022-12-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0015_auto_20221226_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='bottom_sizes',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='M', max_length=30),
        ),
        migrations.AddField(
            model_name='recipient',
            name='top_sizes',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='M', max_length=30),
        ),
    ]
