# Generated by Django 3.2.12 on 2022-12-26 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0016_auto_20221226_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='current_offering',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='texts.productcategory'),
            preserve_default=False,
        ),
    ]
