# Generated by Django 3.2.12 on 2022-12-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0018_auto_20221226_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='bottom_sizes',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=30),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='top_sizes',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=30),
        ),
    ]
